# SPDX-FileCopyrightText: Copyright (c) 2016-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: hone
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  hone:
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 23
      - uses: actions/cache@v6
        with:
          path: ~/.m2/repository
          key: ubuntu-surefire-jdk-23-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-surefire-jdk-23-maven-
      - run: |
          mvn clean install -ntp -Phone --errors --batch-mode
